#define DEFSOUND_VERSION_MAJOR      0
#define DEFSOUND_VERSION_MINOR      1
#define DEFSOUND_VERSION_SUBVERSION 6
#define DEFSOUND_VERSION_BUILDNO    0

#define __DEFSOUND_STR_HELPER2(x)   #x
#define __DEFSOUND_STR_HELPER(x)    __DEFSOUND_STR_HELPER2(x)

#define DEFSOUND_VERSION_BUILD      DEFSOUND_VERSION_MAJOR, DEFSOUND_VERSION_MINOR, DEFSOUND_VERSION_SUBVERSION, DEFSOUND_VERSION_BUILDNO
#define DEFSOUND_VERSION_BUILD_STR  __DEFSOUND_STR_HELPER(DEFSOUND_VERSION_MAJOR.DEFSOUND_VERSION_MINOR.DEFSOUND_VERSION_SUBVERSION.DEFSOUND_VERSION_BUILDNO)
